// GENERATED by scripts/build-data.ts — do not edit. Run `npm run data` instead.
// Derived from Google libaddressinput address data (CC-BY 4.0), snapshot 2026-10-01.
// Format of each entry is documented at the top of scripts/build-data.ts.

/**
 * Countries with postal codes: alpha-2 code + entry, ";"-separated, "#" standing for \d.
 * Minifiers fold the concatenation.
 */
export const RULES =
  "ACASCN1ZZ~c~4 ~~~ASCN 1ZZ;" +
  "ADAD[1-7]0#~N~~~~AD100;" +
  "AF#{4}~N~~~~1001;" +
  "AIAI2640~N~2-~~~AI-2640;" +
  "AL#{4}~N~~~~1001;" +
  "AM(?:37)?#{4}~N~~~46~0010;" +
  "AR[A-HJ-NP-Z]#{4}[A-Z]{3}!#{4}~~!~~48~1070;" +
  "AS96799(?:#{4})?~zRN~5-~~59~96799;" +
  "AT#{4}~RN~~A~~1010;" +
  "AU#{4}~cRN~~~~2060;" +
  "AX22#{3}~RN~~~~22150;" +
  "AZ#{4}~N~~~~1000;" +
  "BA#{5}~N~~~~71000;" +
  "BBBB#{5}~N~~~~BB23026;" +
  "BD#{4}~N~~~~1340;" +
  "BE#{4}~RN~~B~~4000;" +
  "BG#{4}~N~~~~1000;" +
  "BH(?:1[0-2]|[1-9])#{2}~N~~~34~317;" +
  "BL9[78][01]#{2}~RN~~~~97100;" +
  "BM[A-Z]{2}[A-Z0-9]{2}~~2 ~~~FL 07;" +
  "BN[A-Z]{2}#{4}~~~~~BT2328;" +
  "BR#{8}~RN~5-~~~40301-110;" +
  "BT#{5}~N~~~~11001;" +
  "BY#{6}~N~~~~223016;" +
  "CA[ABCEGHJKLMNPRSTVXY]#[ABCEGHJ-NPRSTV-Z]#[ABCEGHJ-NPRSTV-Z]#~R~3 ~~~H3Z 2Y7;" +
  "CC6799~N~~~~6799;" +
  "CH#{4}~RN~~~~2544;" +
  "CL#{7}~N~~~~8340457;" +
  "CN#{6}~RN~~~~266033;" +
  "CO#{6}~N~~~~111221;" +
  "CR#{4,5}!#{7}~~!3-~~47~1000;" +
  "CU#{5}~N~~~~10700;" +
  "CV#{4}~N~~~~7600;" +
  "CX6798~N~~~~6798;" +
  "CY#{4}~N~~~~2008;" +
  "CZ#{5}~RN~3 ~~~100 00;" +
  "DE#{5}~RN~~D~~26133;" +
  "DK#{4}~RN~~~~8660;" +
  "DO#{5}~N~~~~11903;" +
  "DZ#{5}~N~~~~40304;" +
  "EC#{6}~N~~~~090105;" +
  "EE#{5}~RN~~~~69501;" +
  "EG#{7}|#{5}~N~~~57~4460232;" +
  "EH#{5}~N~~~~70000;" +
  "ES#{5}~RN~~E~~28039;" +
  "ET#{4}~N~~~~1000;" +
  "FI#{5}~RN~~~~00550;" +
  "FKFIQQ1ZZ~cR~4 ~~~FIQQ 1ZZ;" +
  "FM9694[1-4](?:#{4})?~zRN~5-~~59~96941;" +
  "FO#{3}~N~~~~100;" +
  "FR#{5}~RN~~F~~33380;" +
  "GBGIR0AA|(?:A[BL]|B[ABDFHLNR-TX]?|C[ABFHMORTVW]|D[ADEGHLNTY]|E[CHNX]?|F[KY]|G[LUY]?|H[ADGPRSUX]|I[GMPV]|JE|K[ATWY]|L[ADELNSU]?|M[EKL]?|N[EGNPRW]?|O[LX]|P[AEHLOR]|R[GHM]|S[AEGK-PR-TWY]?|T[ADFNQ-SW]|UB|W[ACDFNRSV]?|YO|ZE)#[#A-Z]?#[ABD-HJLN-UW-Z]{2}!BFPO#{1,4}~cR~-3 !4 ~~58~EC1Y 8SY;" +
  "GE#{4}~N~~~~0101;" +
  "GF9[78]3#{2}~RN~~~~97300;" +
  "GGGY#[#A-Z]?#[ABD-HJLN-UW-Z]{2}~cR~-3 ~~67~GY1 1AA;" +
  "GIGX111AA~c~4 ~~~GX11 1AA;" +
  "GL39#{2}~RN~~~~3900;" +
  "GN#{3}~N~~~~001;" +
  "GP9[78][01]#{2}~RN~~~~97100;" +
  "GR#{5}~RN~3 ~~~151 24;" +
  "GSSIQQ1ZZ~cR~4 ~~~SIQQ 1ZZ;" +
  "GT#{5}~N~~~~09001;" +
  "GU969(?:[12]#|3[12])(?:#{4})?~zRN~5-~~59~96910;" +
  "GW#{4}~N~~~~1000;" +
  "HM#{4}~N~~~~7050;" +
  "HN#{5}~N~~~~31301;" +
  "HR#{5}~N~~~~10000;" +
  "HT#{4}~N~~~~6120;" +
  "HU#{4}~RN~~H~~1037;" +
  "ID#{5}~N~~~~40115;" +
  "IE(?:[AC-FHKNPRTV-Y]#{2}|D6W)[#AC-FHKNPRTV-Y]{4}~e~3 ~~~A65 F4E2;" +
  "IL#{5}(?:#{2})?~N~~~57~9614303;" +
  "IMIM#[#A-Z]?#[ABD-HJLN-UW-Z]{2}~cR~-3 ~~67~IM2 1AA;" +
  "IN#{6}~pRN~~~~110034;" +
  "IOBBND1ZZ~cR~4 ~~~BBND 1ZZ;" +
  "IQ#{5}~N~~~~31001;" +
  "IR#{10}~N~5-~~~11936-12345;" +
  "IS#{3}~N~~~~320;" +
  "IT#{5}~RN~~I~~00144;" +
  "JEJE#[#A-Z]?#[ABD-HJLN-UW-Z]{2}~cR~-3 ~~67~JE1 1AA;" +
  "JO#{5}~N~~~~11937;" +
  "JP#{7}~RN~3-~~~154-0023;" +
  "KE#{5}~N~~~~20100;" +
  "KG#{6}~N~~~~720001;" +
  "KH#{5,6}~N~~~56~120101;" +
  "KR#{5}~RN~~~~03051;" +
  "KW#{5}~N~~~~54541;" +
  "KYKY#{5}~N~3-~~~KY1-1100;" +
  "KZ#{6}~N~~~~040900;" +
  "LA#{5}~N~~~~01160;" +
  "LB#{4}(?:#{4})?~N~4 ~~48~2038 3054;" +
  "LI948[5-9]|949[0-8]~RN~~FL~~9496;" +
  "LK#{5}~N~~~~20000;" +
  "LR#{4}~N~~~~1000;" +
  "LS#{3}~N~~~~100;" +
  "LT#{5}~RN~~~~04340;" +
  "LU#{4}~RN~~L~~4750;" +
  "LVLV#{4}~RN~2-~~~LV-1073;" +
  "MA#{5}~N~~~~53000;" +
  "MC980#{2}~N~~~~98000;" +
  "MD#{4}~N~~~~2012;" +
  "ME8#{4}~N~~~~81257;" +
  "MF9[78][01]#{2}~RN~~~~97100;" +
  "MG#{3}~N~~~~501;" +
  "MH969[67]#(?:#{4})?~zRN~5-~~59~96960;" +
  "MK#{4}~N~~~~1314;" +
  "MM#{5}~N~~~~11181;" +
  "MN#{5}~N~~~~65030;" +
  "MP9695[012](?:#{4})?~zRN~5-~~59~96950;" +
  "MQ9[78]2#{2}~RN~~~~97220;" +
  "MT[A-Z]{3}#{2,4}~~3 ~~57~NXR 01;" +
  "MU#{3}(?:#{2}|[A-Z]{2}#{3})~~~~58~42602;" +
  "MV#{5}~N~~~~20026;" +
  "MX#{5}~RN~~~~02860;" +
  "MY#{5}~RN~~~~43000;" +
  "MZ#{4}~N~~~~1102;" +
  "NA#{5}~N~~~~10001;" +
  "NC988#{2}~RN~~~~98814;" +
  "NE#{4}~N~~~~8001;" +
  "NF2899~N~~~~2899;" +
  "NG#{6}~N~~~~930283;" +
  "NI#{5}~N~~~~52000;" +
  "NL[1-9]#{3}(?:[A-RT-Z][A-Z]|S[BCE-RT-Z])~R~4 ~~~1234 AB;" +
  "NO#{4}~RN~~N~~0025;" +
  "NP#{5}~N~~~~44601;" +
  "NZ#{4}~cRN~~~~6001;" +
  "OM#{3}~N~~PC~~133;" +
  "PE[0-2]#{4}!LIMA#{1,2}!CALLAO0?#~~!4 !6 ~~58~02001;" +
  "PF987#{2}~RN~~~~98709;" +
  "PG#{3}~N~~~~111;" +
  "PH#{4}~N~~~~1008;" +
  "PK#{5}~N~~~~44000;" +
  "PL#{5}~RN~2-~~~00-950;" +
  "PM9[78]5#{2}~RN~~~~97500;" +
  "PNPCRN1ZZ~cR~4 ~~~PCRN 1ZZ;" +
  "PR00[679]#{2}(?:#{4})?~zRN~5-~~59~00930;" +
  "PT#{7}~RN~4-~P~~2725-079;" +
  "PW969(?:39|40)(?:#{4})?~zRN~5-~~59~96940;" +
  "PY#{6}~N~~~~001001;" +
  "RE9[78]4#{2}~RN~~~~97400;" +
  "RO#{6}~RN~~~~060274;" +
  "RS#{5,6}~N~~~56~106314;" +
  "RU#{6}~RN~~~~247112;" +
  "SA#{5}~N~~~~11564;" +
  "SD#{5}~N~~~~11042;" +
  "SE#{5}~RN~3 ~S~~114 55;" +
  "SG#{6}~RN~~~~546080;" +
  "SH(?:ASCN|STHL)1ZZ~cR~4 ~~~STHL 1ZZ;" +
  "SI#{4}~N~~~~4000;" +
  "SJ#{4}~RN~~~~9170;" +
  "SK#{5}~RN~3 ~~~010 01;" +
  "SM4789#~RN~~~~47890;" +
  "SN#{5}~N~~~~12500;" +
  "SO[A-Z]{2}#{5}~~2 ~~~JH 09010;" +
  "SV[1-3][1-7][0-2]#~N~~~~1101;" +
  "SZ[HLMS]#{3}~~~~~H100;" +
  "TATDCU1ZZ~c~4 ~~~TDCU 1ZZ;" +
  "TCTKCA1ZZ~cR~4 ~~~TKCA 1ZZ;" +
  "TH#{5}~N~~~~10150;" +
  "TJ#{6}~N~~~~735450;" +
  "TM#{6}~N~~~~744000;" +
  "TN#{4}~N~~~~1002;" +
  "TR#{5}~RN~~~~01960;" +
  "TT#{6}~N~~~~500234;" +
  "TW#{3}(?:#{2,3})?~RN~~~36~104;" +
  "TZ#{4,5}~N~~~45~6090;" +
  "UA#{5}~RN~~~~15432;" +
  "UM96898~zN~~~~96898;" +
  "US#{5}(?:#{4})?~zRN~5-~~59~95014;" +
  "UY#{5}~N~~~~11600;" +
  "UZ#{6}~N~~~~702100;" +
  "VA00120~N~~~~00120;" +
  "VCVC#{4}~N~~~~VC0100;" +
  "VE#{4}~N~~~~1010;" +
  "VGVG#{4}~N~~~~VG1110;" +
  "VI008(?:[0-4]#|5[01])(?:#{4})?~zRN~5-~~59~00802-1222;" +
  "VN#{5,6}~N~~~56~70010;" +
  "WF986#{2}~RN~~~~98600;" +
  "XK[1-7]#{4}~N~~~~10000;" +
  "YT976#{2}~RN~~~~97600;" +
  "ZA#{4}~RN~~~~0083;" +
  "ZM#{5}~N~~~~50100";

/** Countries without a postal code system, concatenated alpha-2 codes. */
export const NONE = "AEAGAOAQAWBFBIBJBOBQBSBVBWBZCDCFCGCICKCMCWDJDMERFJGAGDGHGMGQGYHKJMKIKMKNKPLCLYMLMOMRMSMWNRNUPAPSQARWSBSCSLSRSSSTSXSYTDTFTGTKTLTOTVUGVUWSYEZW";

/**
 * Alpha-3 codes in alphabetical order of their alpha-2 codes. A lowercase letter
 * means "alpha-2 + this letter" (DE + u = DEU); otherwise three uppercase letters.
 */
export const ALPHA3 = "ASCANDAREgATGabARMAGOATAgmAUTsABWALAeBIHBRBBGDlarrBDIBENmuBRNlBESaBHSntaBLRBLZnkCODCAFCOGevCOKCHLrCHNlibCPVCUWrpeuiDNKamauESTyESHiphniFLKFSMFROabrGRDoGUFyabGRLbGINGLPGNQcSGSmmGNBGUYgddvinnIRLISRndtIRQnlayJAMrnnzmrCOMaPRKKORtCYMKAZonaeaLBRouxaLBYroaMNEMAFMDGldirgMACMNPMTQtrMLTsMDViMEXsMOZmlrkacdrluNIUlnnrPYFPNGlPAKPOLSPMPCNiePRTPLWPRYtuuSRBsauSLBSYCnSWEpnSVNmSVKerSENmSURdpSLVmrSWZaaTCDATFoaklsTKMTUNnTURoTUVnaUKRaiaURYbttnbrmtWLFmxmMYTfbe";

/** ISO 3166-1 alpha-2 code of a supported country or territory (252, including XK for Kosovo). */
export type CountryCode =
  | "AC"
  | "AD"
  | "AE"
  | "AF"
  | "AG"
  | "AI"
  | "AL"
  | "AM"
  | "AO"
  | "AQ"
  | "AR"
  | "AS"
  | "AT"
  | "AU"
  | "AW"
  | "AX"
  | "AZ"
  | "BA"
  | "BB"
  | "BD"
  | "BE"
  | "BF"
  | "BG"
  | "BH"
  | "BI"
  | "BJ"
  | "BL"
  | "BM"
  | "BN"
  | "BO"
  | "BQ"
  | "BR"
  | "BS"
  | "BT"
  | "BV"
  | "BW"
  | "BY"
  | "BZ"
  | "CA"
  | "CC"
  | "CD"
  | "CF"
  | "CG"
  | "CH"
  | "CI"
  | "CK"
  | "CL"
  | "CM"
  | "CN"
  | "CO"
  | "CR"
  | "CU"
  | "CV"
  | "CW"
  | "CX"
  | "CY"
  | "CZ"
  | "DE"
  | "DJ"
  | "DK"
  | "DM"
  | "DO"
  | "DZ"
  | "EC"
  | "EE"
  | "EG"
  | "EH"
  | "ER"
  | "ES"
  | "ET"
  | "FI"
  | "FJ"
  | "FK"
  | "FM"
  | "FO"
  | "FR"
  | "GA"
  | "GB"
  | "GD"
  | "GE"
  | "GF"
  | "GG"
  | "GH"
  | "GI"
  | "GL"
  | "GM"
  | "GN"
  | "GP"
  | "GQ"
  | "GR"
  | "GS"
  | "GT"
  | "GU"
  | "GW"
  | "GY"
  | "HK"
  | "HM"
  | "HN"
  | "HR"
  | "HT"
  | "HU"
  | "ID"
  | "IE"
  | "IL"
  | "IM"
  | "IN"
  | "IO"
  | "IQ"
  | "IR"
  | "IS"
  | "IT"
  | "JE"
  | "JM"
  | "JO"
  | "JP"
  | "KE"
  | "KG"
  | "KH"
  | "KI"
  | "KM"
  | "KN"
  | "KP"
  | "KR"
  | "KW"
  | "KY"
  | "KZ"
  | "LA"
  | "LB"
  | "LC"
  | "LI"
  | "LK"
  | "LR"
  | "LS"
  | "LT"
  | "LU"
  | "LV"
  | "LY"
  | "MA"
  | "MC"
  | "MD"
  | "ME"
  | "MF"
  | "MG"
  | "MH"
  | "MK"
  | "ML"
  | "MM"
  | "MN"
  | "MO"
  | "MP"
  | "MQ"
  | "MR"
  | "MS"
  | "MT"
  | "MU"
  | "MV"
  | "MW"
  | "MX"
  | "MY"
  | "MZ"
  | "NA"
  | "NC"
  | "NE"
  | "NF"
  | "NG"
  | "NI"
  | "NL"
  | "NO"
  | "NP"
  | "NR"
  | "NU"
  | "NZ"
  | "OM"
  | "PA"
  | "PE"
  | "PF"
  | "PG"
  | "PH"
  | "PK"
  | "PL"
  | "PM"
  | "PN"
  | "PR"
  | "PS"
  | "PT"
  | "PW"
  | "PY"
  | "QA"
  | "RE"
  | "RO"
  | "RS"
  | "RU"
  | "RW"
  | "SA"
  | "SB"
  | "SC"
  | "SD"
  | "SE"
  | "SG"
  | "SH"
  | "SI"
  | "SJ"
  | "SK"
  | "SL"
  | "SM"
  | "SN"
  | "SO"
  | "SR"
  | "SS"
  | "ST"
  | "SV"
  | "SX"
  | "SY"
  | "SZ"
  | "TA"
  | "TC"
  | "TD"
  | "TF"
  | "TG"
  | "TH"
  | "TJ"
  | "TK"
  | "TL"
  | "TM"
  | "TN"
  | "TO"
  | "TR"
  | "TT"
  | "TV"
  | "TW"
  | "TZ"
  | "UA"
  | "UG"
  | "UM"
  | "US"
  | "UY"
  | "UZ"
  | "VA"
  | "VC"
  | "VE"
  | "VG"
  | "VI"
  | "VN"
  | "VU"
  | "WF"
  | "WS"
  | "XK"
  | "YE"
  | "YT"
  | "ZA"
  | "ZM"
  | "ZW";
